//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TTPV2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Event_ttp
    {
        public int IdEvt { get; set; }
        public string TitreEvt { get; set; }
        public string LocEvt { get; set; }
        public System.DateTime DateEvt { get; set; }
        public string PhotoEvt { get; set; }
        public bool EtatEvt { get; set; }
        public Nullable<int> NbMaxParticipants { get; set; }
        public string UserNameAdmin { get; set; }
    
        public virtual Participants Participants { get; set; }
    }
}
