//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TTPV2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Participants
    {
        public int IdEvt { get; set; }
        public string UserNamePart { get; set; }
    
        public virtual Event_ttp Event_ttp { get; set; }
        public virtual User_ttp User_ttp { get; set; }
    }
}
